CREATE DATABASE  bms6_db;
USE bms6_db;
SHOW TABLES;
CREATE TABLE dept(Dno int,Dname varchar(30),Dloc varchar(30));
DESC dept;
INSERT into DEPT values(10,'Admin','Bangalore');
commit;
SELECT * FROM dept;
CREATE TABLE Person(driver_id varchar(10),name varchar(20),address varchar(30),primary key(driver_id));
DESC Person;
CREATE TABLE car(reg_num varchar(10),model varchar(10),year int, primary key(reg_num));
DESC car;
CREATE TABLE accident(report_num int, accident_date date, location varchar(20),primary key(report_num));
DESC accident;
CREATE TABLE owns(driver_id varchar(10),reg_num varchar(10),primary key(driver_id, reg_num),foreign key(driver_id) references person(driver_id),foreign key(reg_num) references car(reg_num));
DESC owns;
CREATE TABLE participated(driver_id varchar(10), reg_num varchar(10),report_num int, damage_amount int, primary key(driver_id, reg_num, report_num),foreign key(driver_id) references person(driver_id),foreign key(reg_num) references car(reg_num),foreign key(report_num) references accident(report_num));
DESC participated;
INSERT INTO person VALUES('&driver_id','&name','&address');
COMMIT;
SELECT * FROM person;
INSERT INTO car VALUES('&reg_num','&model', year);
COMMIT;
SELECT * FROM car;
INSERT INTO accident VALUES('&report_num','&accident_date','&location');
COMMIT;
SELECT * FROM accident;
INSERT INTO owns VALUES ('&driver_id','&reg_num');
commit;
SELECT * FROM owns;
INSERT INTO participated VALUES ('&driver_id','&reg_num','&report_num', '&damage_amount');
COMMIT;
SELECT * FROM participated;
commit;
SELECT * FROM participated;
INSERT INTO accident VALUES(16,'15-MAR-08','Domlur');
SELECT * FROM accident;
SELECT COUNT(distinct driver_id) CNT FROM participated a, accident b WHERE a.report_num=b.report_num AND b.accident_date LIKE '%08';
SELECT COUNT(report_num) CNT FROM car c,participated p WHERE c.reg_num=p.reg_num AND model='Lancer';